server:
  port: 8080

spring:
  application:
    name: online-taxi-api-passenger

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/,http://localhost:7901/eureka/,http://localhost:7902/eureka/
    registry-fetch-interval-seconds: 30
  instance:
    lease-renewal-interval-in-seconds: 30

logging:
  level:
    root: info



